# Generated by Django 4.1.7 on 2023-03-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spotify_token',
            field=models.CharField(default='BQAfT4cVMK0DXKZxo7oPQIQ5D6luUcFdnjvQrnHpfY1hqGvJEAW0eeA4al7STMq9v3Hegda7iN10OVGE6FO2Z6oJ-BtFAN3RdFxWUJEbNT3BNrcKsWDT', max_length=225),
        ),
    ]
