# Generated by Django 4.1.7 on 2023-03-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_spotify_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='spotify_token',
        ),
    ]
