# Generated by Django 4.1.7 on 2023-03-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album_collections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album_collection',
            old_name='user_id',
            new_name='user',
        ),
    ]
